name: Update Docker Hub Readme
on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - '.github/workflows/update-docker-readme.yml'
  workflow_dispatch:

jobs:
  update-docker-readme:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.1

    - name: Update Docker Hub Readme (buanet)
      uses: peter-evans/dockerhub-description@v3.4.2
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASS }}
        repository: marcinio/iobroker_marc
        short-description: Official Docker image for ioBroker based on Debian Bullseye slim 
        readme-filepath: ./docs/README_docker_hub_buanet.md
